# import = [
#   "./themes/tokyo-night.toml",
#   "./keybinds.toml",
# ]

working_directory = "None"

live_config_reload =  false

# [shell]
# program = ""
# args = [""]

[env]


[window]
# dimensions = { columns = , lines = }
position = { x = 960, y = 0}
padding = { x = 10, y = 30}
# dynamic_padding = { x = , y =}
decorations = "None"
opacity = 0.95
startup_mode = "Windowed"
# title = ""
# dynamic_title =
decorations_theme_variant = "Dark"
# resize_increments =

[font]
normal = { family = "JetBrainsMonoNL Nerd Font" , style = "Regular" }
size = 17
# offset = { x= ,y=}
# glyph_offset = {x=,y=}

[selection]
# semantic_escape_chars = ""
save_to_clipboard = true

[cursor]
# style = {shape = "", blinking = "On" }
#vi_mode_style = { shape = "Beam", blinking = "On" }
blink_interval = 750
blink_timeout = 10
unfocused_hollow = true
thickness = 1
