working_directory = "None"

live_config_reload =  false

[window]
position = { x = 960, y = 0}
padding = { x = 10, y = 30}
decorations = "None"
opacity = 0.95
startup_mode = "Windowed"
decorations_theme_variant = "Dark"

[font]
normal = { family = "FiraCode Nerd Font" , style = "Regular" }
size = 17

[selection]
save_to_clipboard = true

