# general

# import = ["<string>",]
import = [
"~/.config/alacritty/base16-dark.toml",
"~/.config/alacritty/keybindings.toml",
]

# shell = "<string>" | { program = "<string>", args = ["<string>",] }
[shell]
program = "/usr/bin/zsh"
args = ['--login -c "tmux new -A -s home"']

# working_directory = "<string>" | "None"
working_directory = "None"

# live_config_reload = true | false
live_config_reload =  false

# ipc_socket = true | false # (unix only)
ipc_socket = true

# env
[env]

WINIT_X11_SCALE_FACTOR = "1.0"

# window
[window]

# dimensions = { columns = <integer>, lines = <integer> }
dimensions = { column = 0, lines = 0 }

# position = "None" | { x = <integer>, y = <integer> }
position = { x = 960, y = 0}

# { x = <integer>, y = <integer> }
padding = { x = 10, y = 30}

# dynamic_padding = true | false
dynamic_padding = false

# decorations = "Full" | "None" | "Transparent" | "Buttonless"
decorations = "None"

# opacity = <float>
opacity = 0.95

# blur = true | false
blur = false

# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Windowed"

# title = "<string>"

# dynamic_title = true | false

# class = { instance = "<string>", general = "<string>" } # (Linux/BSD only)

# decorations_theme_variant = "Dark" | "Light" | "None"
decorations_theme_variant = "Dark"

# resize_increments =

# scrolling

# history = <integer>

# multiplier = <integer>

# font
[font]

# normal = { family = "<string>", style = "<string>" }
normal = { family = "JetBrainsMonoNL Nerd Font" , style = "Regular" }

# bold = { family = "<string>", style = "<string>" }

# italic = { family = "<string>", style = "<string>" }

# bold_italic = { family = "<string>", style = "<string>" }

# size = <float>
size = 17

# offset = { x = <integer>, y = <integer> }

# glyph_offset = { x = <integer>, y = <integer> }

# builtin_box_drawing = true | false

[selection]
# semantic_escape_chars = ""
save_to_clipboard = true

[cursor]
# style = {shape = "", blinking = "On" }
#vi_mode_style = { shape = "Beam", blinking = "On" }
blink_interval = 750
blink_timeout = 10
unfocused_hollow = true
thickness = 1
